"""empty message

Revision ID: 8c33844dbccd
Revises: 2077491f3174
Create Date: 2022-09-19 13:47:26.367462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c33844dbccd'
down_revision = '2077491f3174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cars', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'cars', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='unique')
    op.drop_column('cars', 'updated_at')
    op.drop_column('cars', 'created_at')
    # ### end Alembic commands ###
